[cisco_switches]
Core_Switch_01 ansible_host=192.168.1.1
Access_Switch_01 ansible_host=192.168.1.2

[cisco_switches:vars]
ansible_network_os=cisco.ios.ios
ansible_user=admin
ansible_ssh_pass=ciscotest
